
package project.feukora.webservice.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeukoraServiceService", targetNamespace = "http://model.webservice.feukora.project/", wsdlLocation = "http://localhost:9090/project.feukora.webservice?wsdl")
public class FeukoraServiceService
    extends Service
{

    private final static URL FEUKORASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FEUKORASERVICESERVICE_EXCEPTION;
    private final static QName FEUKORASERVICESERVICE_QNAME = new QName("http://model.webservice.feukora.project/", "FeukoraServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/project.feukora.webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEUKORASERVICESERVICE_WSDL_LOCATION = url;
        FEUKORASERVICESERVICE_EXCEPTION = e;
    }

    public FeukoraServiceService() {
        super(__getWsdlLocation(), FEUKORASERVICESERVICE_QNAME);
    }

    public FeukoraServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEUKORASERVICESERVICE_QNAME, features);
    }

    public FeukoraServiceService(URL wsdlLocation) {
        super(wsdlLocation, FEUKORASERVICESERVICE_QNAME);
    }

    public FeukoraServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEUKORASERVICESERVICE_QNAME, features);
    }

    public FeukoraServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeukoraServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFeukoraService
     */
    @WebEndpoint(name = "FeukoraServicePort")
    public IFeukoraService getFeukoraServicePort() {
        return super.getPort(new QName("http://model.webservice.feukora.project/", "FeukoraServicePort"), IFeukoraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFeukoraService
     */
    @WebEndpoint(name = "FeukoraServicePort")
    public IFeukoraService getFeukoraServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model.webservice.feukora.project/", "FeukoraServicePort"), IFeukoraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEUKORASERVICESERVICE_EXCEPTION!= null) {
            throw FEUKORASERVICESERVICE_EXCEPTION;
        }
        return FEUKORASERVICESERVICE_WSDL_LOCATION;
    }

}
