
package project.feukora.webservice.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFeukoraService", targetNamespace = "http://model.webservice.feukora.project/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFeukoraService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.LoginResponse")
    @Action(input = "http://model.webservice.feukora.project/IFeukoraService/loginRequest", output = "http://model.webservice.feukora.project/IFeukoraService/loginResponse")
    public boolean login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<project.feukora.webservice.model.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomers", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.GetCustomers")
    @ResponseWrapper(localName = "getCustomersResponse", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.GetCustomersResponse")
    @Action(input = "http://model.webservice.feukora.project/IFeukoraService/getCustomersRequest", output = "http://model.webservice.feukora.project/IFeukoraService/getCustomersResponse")
    public List<Customer> getCustomers();

    /**
     * 
     * @return
     *     returns project.feukora.webservice.model.Rapport
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRapport", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.CreateRapport")
    @ResponseWrapper(localName = "createRapportResponse", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.CreateRapportResponse")
    @Action(input = "http://model.webservice.feukora.project/IFeukoraService/createRapportRequest", output = "http://model.webservice.feukora.project/IFeukoraService/createRapportResponse")
    public Rapport createRapport();

    /**
     * 
     * @param rapport
     */
    @WebMethod
    @RequestWrapper(localName = "saveRapport", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.SaveRapport")
    @ResponseWrapper(localName = "saveRapportResponse", targetNamespace = "http://model.webservice.feukora.project/", className = "project.feukora.webservice.model.SaveRapportResponse")
    @Action(input = "http://model.webservice.feukora.project/IFeukoraService/saveRapportRequest", output = "http://model.webservice.feukora.project/IFeukoraService/saveRapportResponse")
    public void saveRapport(
        @WebParam(name = "rapport", targetNamespace = "")
        Rapport rapport);

}
